# Generated by Django 4.2.5 on 2023-09-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_remove_order_user_order_customer_order_delivery_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='LittleLemonAPI.cart'),
        ),
    ]
