# Generated by Django 4.2.5 on 2023-09-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_remove_order_carts_order_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carts',
            new_name='items',
        ),
    ]
