# Generated by Django 4.2.5 on 2023-09-09 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonAPI', '0007_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_crew',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='crew_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
